name: Run tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"

      - name: Install dependencies
        run: |
          pip install -r requirements/test.txt
      - name: Run all tests
        run: |
          pytest
